### ISSUE TITLE
How RRTXPlanner.hpp is used

### ISSUE THREAD

**Issue by ayoubraji** [godicked/catkin_ws#1]
I'm checking the code because I'm interested in rrtx for a dubins car like robot planning and obstacles avoidance.
I don't understand the purpose of the RRTXPlanner.hpp and cpp code.  Are they only part of an initial attempt for the rrtxnode? Because I've seen that the rrtx_node works only thanks to the main rrtx algorithm and the publisher.

Furthermore, have you tested the code in simulation or in a car like robot?
Thank you

**Comment by godicked** [comment]
The RRTXPlanner is a prototype for a global planner as plugin for nav_core and the rrtxnode as a standalone node for ROS.

I've tested this code and the ompl rrtstar on a model car. 
The rrtstar code is more optimized (obstacle detection on edges only if they are more optimal) and therefore faster in practice.  

http://wiki.ros.org/nav_core
http://ompl.kavrakilab.org/classompl_1_1geometric_1_1RRTstar.html
https://github.com/AutoModelCar/AutoModelCarWiki/wiki/Hardware-(AutoNOMOS-Model-v3)

**Comment by ayoubraji** [comment]
Now it's clear. 
The rrtstar is optimized but I'll try the rrtx because I'm searching a solution for a dynamic environment, in which obstacles could be in movement.
Thank you for the references.

**Comment by ayoubraji** [comment]
Thank you for the openness
